// Monaco editor theme definitions for the built-in theme switcher

export interface MonacoThemeDefinition {
  id: string;
  name: string;
  icon: string;
  base: "vs-dark" | "vs";
  colors: Record<string, string>;
  rules: Array<{ token: string; foreground?: string; fontStyle?: string }>;
}

export const MONACO_THEMES: MonacoThemeDefinition[] = [
  {
    id: "codeforge-dark",
    name: "CodeForge Dark",
    icon: "⚡",
    base: "vs-dark",
    colors: {
      "editor.background": "#0a0f1a",
      "editor.foreground": "#e2e8f0",
      "editor.lineHighlightBackground": "#1a2332",
      "editor.selectionBackground": "#264f78",
      "editorCursor.foreground": "#22d3ee",
      "editorLineNumber.foreground": "#4a5568",
      "editorLineNumber.activeForeground": "#22d3ee",
      "editor.selectionHighlightBackground": "#264f7844",
      "editorIndentGuide.background": "#1e293b",
      "editorIndentGuide.activeBackground": "#334155",
    },
    rules: [
      { token: "comment", foreground: "6b7280", fontStyle: "italic" },
      { token: "keyword", foreground: "c084fc" },
      { token: "string", foreground: "34d399" },
      { token: "number", foreground: "f59e0b" },
      { token: "type", foreground: "22d3ee" },
      { token: "function", foreground: "60a5fa" },
      { token: "variable", foreground: "e2e8f0" },
      { token: "operator", foreground: "94a3b8" },
      { token: "tag", foreground: "f87171" },
      { token: "attribute.name", foreground: "fbbf24" },
      { token: "attribute.value", foreground: "34d399" },
      { token: "delimiter", foreground: "94a3b8" },
    ],
  },
  {
    id: "dracula",
    name: "Dracula",
    icon: "🧛",
    base: "vs-dark",
    colors: {
      "editor.background": "#282a36",
      "editor.foreground": "#f8f8f2",
      "editor.lineHighlightBackground": "#44475a",
      "editor.selectionBackground": "#44475a",
      "editorCursor.foreground": "#f8f8f2",
      "editorLineNumber.foreground": "#6272a4",
      "editorLineNumber.activeForeground": "#f8f8f2",
      "editor.selectionHighlightBackground": "#44475a55",
      "editorIndentGuide.background": "#3b3d4f",
      "editorIndentGuide.activeBackground": "#6272a4",
    },
    rules: [
      { token: "comment", foreground: "6272a4", fontStyle: "italic" },
      { token: "keyword", foreground: "ff79c6" },
      { token: "string", foreground: "f1fa8c" },
      { token: "number", foreground: "bd93f9" },
      { token: "type", foreground: "8be9fd", fontStyle: "italic" },
      { token: "function", foreground: "50fa7b" },
      { token: "variable", foreground: "f8f8f2" },
      { token: "operator", foreground: "ff79c6" },
      { token: "tag", foreground: "ff79c6" },
      { token: "attribute.name", foreground: "50fa7b" },
      { token: "attribute.value", foreground: "f1fa8c" },
      { token: "delimiter", foreground: "f8f8f2" },
    ],
  },
  {
    id: "nord",
    name: "Nord",
    icon: "❄️",
    base: "vs-dark",
    colors: {
      "editor.background": "#2e3440",
      "editor.foreground": "#d8dee9",
      "editor.lineHighlightBackground": "#3b4252",
      "editor.selectionBackground": "#434c5e",
      "editorCursor.foreground": "#d8dee9",
      "editorLineNumber.foreground": "#4c566a",
      "editorLineNumber.activeForeground": "#d8dee9",
      "editor.selectionHighlightBackground": "#434c5e55",
      "editorIndentGuide.background": "#3b4252",
      "editorIndentGuide.activeBackground": "#4c566a",
    },
    rules: [
      { token: "comment", foreground: "616e88", fontStyle: "italic" },
      { token: "keyword", foreground: "81a1c1" },
      { token: "string", foreground: "a3be8c" },
      { token: "number", foreground: "b48ead" },
      { token: "type", foreground: "8fbcbb" },
      { token: "function", foreground: "88c0d0" },
      { token: "variable", foreground: "d8dee9" },
      { token: "operator", foreground: "81a1c1" },
      { token: "tag", foreground: "81a1c1" },
      { token: "attribute.name", foreground: "8fbcbb" },
      { token: "attribute.value", foreground: "a3be8c" },
      { token: "delimiter", foreground: "eceff4" },
    ],
  },
  {
    id: "monokai-pro",
    name: "Monokai Pro",
    icon: "🎨",
    base: "vs-dark",
    colors: {
      "editor.background": "#2d2a2e",
      "editor.foreground": "#fcfcfa",
      "editor.lineHighlightBackground": "#3a383d",
      "editor.selectionBackground": "#5b595c",
      "editorCursor.foreground": "#fcfcfa",
      "editorLineNumber.foreground": "#5b595c",
      "editorLineNumber.activeForeground": "#c1c0c0",
      "editor.selectionHighlightBackground": "#5b595c55",
      "editorIndentGuide.background": "#3a383d",
      "editorIndentGuide.activeBackground": "#5b595c",
    },
    rules: [
      { token: "comment", foreground: "727072", fontStyle: "italic" },
      { token: "keyword", foreground: "ff6188" },
      { token: "string", foreground: "ffd866" },
      { token: "number", foreground: "ab9df2" },
      { token: "type", foreground: "78dce8", fontStyle: "italic" },
      { token: "function", foreground: "a9dc76" },
      { token: "variable", foreground: "fcfcfa" },
      { token: "operator", foreground: "ff6188" },
      { token: "tag", foreground: "ff6188" },
      { token: "attribute.name", foreground: "78dce8" },
      { token: "attribute.value", foreground: "ffd866" },
      { token: "delimiter", foreground: "939293" },
    ],
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    icon: "🐙",
    base: "vs-dark",
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#c9d1d9",
      "editor.lineHighlightBackground": "#161b22",
      "editor.selectionBackground": "#264f78",
      "editorCursor.foreground": "#c9d1d9",
      "editorLineNumber.foreground": "#484f58",
      "editorLineNumber.activeForeground": "#c9d1d9",
      "editor.selectionHighlightBackground": "#264f7855",
      "editorIndentGuide.background": "#21262d",
      "editorIndentGuide.activeBackground": "#30363d",
    },
    rules: [
      { token: "comment", foreground: "8b949e", fontStyle: "italic" },
      { token: "keyword", foreground: "ff7b72" },
      { token: "string", foreground: "a5d6ff" },
      { token: "number", foreground: "79c0ff" },
      { token: "type", foreground: "ffa657" },
      { token: "function", foreground: "d2a8ff" },
      { token: "variable", foreground: "c9d1d9" },
      { token: "operator", foreground: "ff7b72" },
      { token: "tag", foreground: "7ee787" },
      { token: "attribute.name", foreground: "79c0ff" },
      { token: "attribute.value", foreground: "a5d6ff" },
      { token: "delimiter", foreground: "c9d1d9" },
    ],
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin",
    icon: "🐱",
    base: "vs-dark",
    colors: {
      "editor.background": "#1e1e2e",
      "editor.foreground": "#cdd6f4",
      "editor.lineHighlightBackground": "#313244",
      "editor.selectionBackground": "#45475a",
      "editorCursor.foreground": "#f5e0dc",
      "editorLineNumber.foreground": "#585b70",
      "editorLineNumber.activeForeground": "#cdd6f4",
      "editor.selectionHighlightBackground": "#45475a55",
      "editorIndentGuide.background": "#313244",
      "editorIndentGuide.activeBackground": "#45475a",
    },
    rules: [
      { token: "comment", foreground: "6c7086", fontStyle: "italic" },
      { token: "keyword", foreground: "cba6f7" },
      { token: "string", foreground: "a6e3a1" },
      { token: "number", foreground: "fab387" },
      { token: "type", foreground: "89dceb" },
      { token: "function", foreground: "89b4fa" },
      { token: "variable", foreground: "cdd6f4" },
      { token: "operator", foreground: "89dceb" },
      { token: "tag", foreground: "f38ba8" },
      { token: "attribute.name", foreground: "f9e2af" },
      { token: "attribute.value", foreground: "a6e3a1" },
      { token: "delimiter", foreground: "bac2de" },
    ],
  },
  {
    id: "github-light",
    name: "GitHub Light",
    icon: "☀️",
    base: "vs",
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#24292f",
      "editor.lineHighlightBackground": "#f6f8fa",
      "editor.selectionBackground": "#0550ae33",
      "editorCursor.foreground": "#24292f",
      "editorLineNumber.foreground": "#8c959f",
      "editorLineNumber.activeForeground": "#24292f",
      "editor.selectionHighlightBackground": "#0550ae22",
      "editorIndentGuide.background": "#d8dee4",
      "editorIndentGuide.activeBackground": "#8c959f",
    },
    rules: [
      { token: "comment", foreground: "6e7781", fontStyle: "italic" },
      { token: "keyword", foreground: "cf222e" },
      { token: "string", foreground: "0a3069" },
      { token: "number", foreground: "0550ae" },
      { token: "type", foreground: "953800" },
      { token: "function", foreground: "8250df" },
      { token: "variable", foreground: "24292f" },
      { token: "operator", foreground: "cf222e" },
      { token: "tag", foreground: "116329" },
      { token: "attribute.name", foreground: "0550ae" },
      { token: "attribute.value", foreground: "0a3069" },
      { token: "delimiter", foreground: "24292f" },
    ],
  },
];

export const DEFAULT_THEME_ID = "codeforge-dark";

export const getThemeById = (id: string): MonacoThemeDefinition | undefined =>
  MONACO_THEMES.find((t) => t.id === id);
